### PR TITLE
Refactored package to use PHPUnit 6 and namespaces

### PR DESCRIPTION
**Pull request by dborsatto**
When using projects that require PHPUnit 6 (with namespaces), this library causes conflicts. This PR addresses this by refactoring the code to use the new version, and moves files to standard folders (`src/` with PSR4 autoloading). This fixes https://github.com/php-vcr/phpunit-testlistener-vcr/issues/20.

This version is a BC break, so a new major version bump would be required (from 2.0 to 3.0).

`PHPUnit/Util/Log/VCR.php` has been renamed `src/VCRTestListener.php` (according to common practices). Unfortunately Git didn't correctly pick up the move, therefore it looks like the previous file has been deleted, and the new one was created. Contents are basically the same, with the refactored use of namespaces and `use` statements.

For end users, upgrading should be as simple as copy/pasting the new configuration in their `phpunit.xml` files, but I can write an upgrade guide.

As I'm seeing low activity around this library (and unfortunately around PHP-VCR as well), I'm prepared to release my forked version, even though I would much rather contribute to the original project.

### CODE REVIEW

**Comment by dborsatto** [comment]
Nothing?

**Comment by tucq88** [comment]
I need this T_T I'm using PHPUnit 6 (and bunch of other packages) T_T Can't get it works without this.

**Comment by dborsatto** [comment]
Yeah, the fact that this is stuck on PHPUnit 5 is the reason why we can't migrate our tests to PHPUnit 6. I'm this close to releasing my fork as standalone.

**Comment by tucq88** [comment]
You should, seems like owner @adri abandoned this project :(

**Comment by dborsatto** [comment]
@Spea, @fedeisas, @tucq88, @GaryJones, @allejo

As there is no activity on this repo any more, I've republished my refactored version of this package, which is PHPUnit 6-compatible, and requires PHP 7. Please test it and let me know if you encounter particular issues.

https://github.com/dborsatto/vcr-phpunit-testlistener

**Comment by adri** [comment]
@dborsatto We're looking for maintainers, see https://github.com/php-vcr/php-vcr/issues/142

**Comment by dborsatto** [comment]
@adri that's for the main package, which unfortunately is too much for me right now, especially as my use case for PHP-VCR is probably one tenth of the scope of the whole project.

With time I'll probably work and release a PSR-7 middleware for Guzzle which does this (that's my use case), but for the time being releasing a custom version of this package is the most viable solution for me.

**Comment by adri** [comment]
Just invited you to the php-vcr organisation @dborsatto. I'm sorry for being inactive. Would be great to see your changes in the main repo.

**Comment by adri** [comment]
@dborsatto This might help https://github.com/eleven-labs/http-replay-plugin/blob/master/composer.json for your use case.

**Pull request closed without merging**
