### PR TITLE
Add php-cs-fixer to check for codestyle fixes

### PR DESCRIPTION
**Pull request by nstapelbroek**
Hey there! 

As discussed in https://github.com/php-vcr/php-vcr/pull/173.
This will install php-cs-fixer as a dev dependency in the project, allowing Travis to check for some easy fixable codestyle violations.

Let me know if you need anything changed.
Cheers!

### CODE REVIEW

**Comment by nstapelbroek** [comment]
Build seems to fail, any thoughts why the Travis project directory is not writable? @renatomefi I'm missing something obvious here :see_no_evil:

**Comment by renatomefi** [comment]
@nstapelbroek I've cleared the cache and started the build again, still the same issue! :/

**Comment by renatomefi** [comment]
Building restarted again, cache cleared, let's see if it helps!

**Comment by renatomefi** [comment]
We better close this one and try again! :/

**Pull request closed without merging**
